### ISSUE TITLE
Use Jinja to handle simple Python expressions in YAML input files

### ISSUE THREAD

**Issue by jaimergp** [insilichem/ommprotocol#7]
Like `conda` does for recipes.

**Comment by ajasja** [comment]
I think that's a great idea. Makeflow is also implementing something similar with their JX format.
http://ccl.cse.nd.edu/software/manuals/jx.html

**Comment by jaimergp** [comment]
Added in commit  5db92fb . See [standard_jinja.yaml](https://github.com/insilichem/ommprotocol/blob/master/examples/standard_jinja.yaml#L75) as an example.
