### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ajasja** [insilichem/ommprotocol#9]
I only found the linux64 build on conda. Any reason why the package would not work on windows?

**Comment by jaimergp** [comment]
I am not building Windows packages because I don't use Windows and I don't have the time to test it, but it *should* work out of the box... After all, `ommprotocol` per se it's a simple Python package. You can build it yourself with `conda build conda-recipe/`, though. If not, take a look at the meta.yaml file and install those packages manually. The following steps *should* work:

```
conda create -n ommprotocol -c omnia openmoltools ruamel_yaml mdtraj openmm parmed
source activate ommprotocol
pip install ommprotocol
# or pip install https://github.com/insilichem/ommprotocol/archive/master.zip for devel version
```

Let me know if it works!

**Comment by ajasja** [comment]
Thanks, that seems to have worked! (I was feeling adventurous and installed OpenMM 7.2 beta and ommprotocol master:)

**Comment by jaimergp** [comment]
Cool! I am testing it myself too... I couldn't resist and installed a VM :P I'll report once I have my results back and maybe upload the conda packages.

**Comment by ajasja** [comment]
Just running `ommprotocol implicit.yaml` with a simple psb structure, I get the error that the force field is not found 
`FileNotFoundError: [Errno 2] No such file or directory: 'c:\\bin\\python\\anaconda64\\envs\\omm\\lib\\site-packages\\simtk\\openmm\\app\\data\\amber99sbildn'` [[full output](https://pastebin.com/37Y9XMaz)]

This is probably openMM fault, although `python -m simtk.testInstallation` does run correctly.

**Comment by jaimergp** [comment]
Can I see your YAML input? Also, can you try using `amber99sbildn.xml` as the forcefield? (Notice the file extension)

**Comment by jaimergp** [comment]
Btw, conda packages for Windows (only Py35 and Py36, though) are available now.

**Comment by ajasja** [comment]
Thanks, that worked! Sorry for the silly mistake, I wasn't sure what the convention was. As a suggestion, could you add complete working examples to the repo under examples (including input files etc...)

**Comment by jaimergp** [comment]
> As a suggestion, could you add complete working examples to the repo under examples (including input files etc...)

Sure. That's some thing on my to-do list. We are preparing the manuscript right now, which will include examples and tests. Once I have something ready, I will upload it to the repo.

**Comment by ajasja** [comment]
Great, that would be nice, since my current system is exploding in OpenMM 
(https://github.com/pandegroup/pdbfixer/issues/92). It can just be an alanine dodecamer or something;)

**Comment by jaimergp** [comment]
Sure. I love systems without ligands, metals or fancy non-natural residues. I will use this, for sure! I'll contact you for further details when I start tackling this.

**Comment by jaimergp** [comment]
Btw, I'll close this issue and open a separate one for the examples thing.
